### ISSUE TITLE
Replace {% trans %} template tag with {% translate %}

### ISSUE THREAD

**Issue by chrisclark** [explorerhq/sql-explorer#567]
Django is moving to the {% translate %} tag.

https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#translate-template-tag

The {% trans %} alias is likely being removed.

**Comment by shiyanshirani** [comment]
Hey! I would love to contribute to this issue and have initiated a PR.

**Comment by shiyanshirani** [comment]
It seems, Django has incorporated the same with `blocktrans` as mentioned in https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#blocktranslate-template-tag, let me know if I should create another issue for this or commit to fix/567

**Comment by marksweb** [comment]
@shiyanshirani wohld be best to do both tags in the same PR

**Comment by marksweb** [comment]
@shiyanshirani yeah translated blocks need doing as well
