### ISSUE TITLE
Search does not work across all queries

### ISSUE THREAD

**Issue by o0StefaniaR0o** [explorerhq/sql-explorer#658]
Hi, 

we have an issue with the "search" feature of SQL explorer.

We currently have a large number of queries, and we often make use of grouping (using prefixes in query titles) when working with queries. 
We are experiencing a usability problem because since version 4 groups appear collapsed by default when the page is loaded.
The search box next to "all queries" only looks for strings in query title that appear in expanded groups, so the search results are often empty or partial.
We have a lot of groups, so it's not feasible for our users to manually expand them every time. 

The possible solutions we see are:
1) Make search look for queries that are not visible (i.e. in a collapsed group)
2) Go back to having the groups expanded by default
3) Have a way to quickly expand all groups

For instance, we may name our queries:
Orders - query1 title
Orders - query2 title
Orders - query3 title

Marketing - query1 title

Users - query1 title
Users - query2 title

When the SQL explorer page is loaded, under "All queries", users see the collapsed groups:
Orders (3)
Marketing (1)
Users (2)

When a user searches for the string "query1" the expected result is:
Orders - query1 title
Marketing - query1 title
Users - query1 title

BUT since groups are not expanded the result is actually empty.

Thanks for the attention, best regards

Stefania

**Comment by chrisclark** [comment]
Should be able to take care of this. Could be ~2 weeks, but I'll bet I can fix it in a point release. Thanks for the feedback!

**Comment by o0StefaniaR0o** [comment]
Thank you Chris!

**Comment by chrisclark** [comment]
Solved here:
https://github.com/explorerhq/sql-explorer/pull/659

Will be released in 5.2 at some point likely next week.

**Comment by o0StefaniaR0o** [comment]
Thank you so much, Chris!

**Comment by chrisclark** [comment]
Addressed in 5.2b1:

https://pypi.org/project/django-sql-explorer/5.2b1/

I will do a final release after I have had this bake for a few days in some prod environments.
