### ISSUE TITLE
Coverage step of CI is failing

### ISSUE THREAD

**Issue by chrisclark** [explorerhq/sql-explorer#671]
One day it was working:

https://github.com/explorerhq/sql-explorer/actions/runs/10620682475/job/29441423460

And then suddenly it was not:

https://github.com/explorerhq/sql-explorer/actions/runs/10793353159/job/29935682005

I'm not aware of any package or GH action upgrades that would have caused it to start failing. It seems quite mysterious to me.

**Comment by marksweb** [comment]
I've seen this [before](https://github.com/marksweb/django-nh3/actions/runs/10673046959/job/29581541100#step:6:22). I still don't really know what it's problem is.

**Comment by chrisclark** [comment]
@marksweb fixed it!! https://github.com/explorerhq/sql-explorer/pull/684/files

**Comment by marksweb** [comment]
@chrisclark I knew there'd be some weird thing like that! 👏🎉
