### ISSUE TITLE
Admin User Id password is NOT working even with fresh installantion

### ISSUE THREAD

**Issue by amit-a8** [explorerhq/sql-explorer#676]
Dear Team,
I have set up SQL explorer in local. Set up was proper but unable to login with user admin password admin.
Kindly help here
Error message - 
Please enter a correct username and password. Note that both fields may be case-sensitive. 
The same issue I got in Mac. Then i set up in Ubuntu 22.04 machine. Error remain same. 

PFA screenshot for more details.

Happy to help if more information is reqd from my end.

REGARDS,
Amit
![Screenshot from 2024-09-19 19-25-38](https://github.com/user-attachments/assets/13bb0cdb-156b-4b5d-99e2-ff3a02d4d4dd)

**Comment by chrisclark** [comment]
Are you running it via `manage.py runserver` or with the docker container?

**Comment by amit-a8** [comment]
Thanks for quick response. 
Yes with manage.py i am able to run by creating new super user. 
In docker container also i faced the same issue. But with manage.py it is working. 

Regards,
Amit

**Comment by amit-a8** [comment]
With docker container also it is working now 

Regards,
Amit
